import Product1 from '../../Image/9.webp'
import Product2 from '../../Image/10.webp'
import Product3 from '../../Image/11.webp'
import Product4 from '../../Image/12.webp'
import Product5 from '../../Image/9.webp'
import Product6 from '../../Image/13.webp'
import Product7 from '../../Image/14.webp'
import Product8 from '../../Image/15.webp'
import Product9 from '../../Image/16.webp'

export const Customer=[
    {
        id:1,
        title:"Customer Testimonial",
        content:"Everybody is different, which is why we offer styles for every body. Laborum fuga incidunt laboriosam voluptas iure, delectus dignissimos facilis neque nulla earum.",
        name:"Petey Cruiser",
        job:"Designer at Colorlib",

    },
    {
        id:2,
        title:"Customer Testimonial",
        content:"Which is why we offer styles for every body. Laborum fuga incidunt laboriosam voluptas iure, delectus dignissimos facilis neque nulla earum.",
        name:"Marry Query",
        job:"Designer at Google",
        
    }
]

export const Productdata=[
    {
        id:1,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:50.00,
        sale:48.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product1,
        type:"Fashion",
        qty:1,
    },
    {
        id:2,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:50.00,
        sale:48.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product2,
        type:"Fashion",
        qty:1,
    },
    {
        id:3,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:50.00,
        sale:48.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product3,
        type:"Fashion",
        qty:1,
    },
    {
        id:4,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:50.00,
        sale:48.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product4,
        type:"Fashion",
        qty:1,
    },
    {
        id:5,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:50.00,
        sale:48.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product5,
        type:"Fashion",
        qty:1,
    },
    {
        id:6,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:50.00,
        sale:48.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product5,
        type:"Fashion",
        qty:1,
    },
    {
        id:7,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:50.00,
        sale:48.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product5,
        type:"Fashion",
        qty:1,
    },
    {
        id:8,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:98.00,
        sale:90.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product6,
        type:"Fashion",
        qty:1,
    },
    {
        id:9,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:98.00,
        sale:90.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product7,
        type:"Skillcare",
        qty:1,
    },    {
        id:10,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:98.00,
        sale:90.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product6,
        type:"Skillcare",
        qty:1,
    },    {
        id:11,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:98.00,
        sale:90.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product8,
        type:"Skillcare",
        qty:1,
    },    {
        id:12,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:98.00,
        sale:90.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product9,
        type:"Skillcare",
        qty:1,
    },    {
        id:13,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:98.00,
        sale:90.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product6,
        type:"Skillcare",
        qty:1,
    },    {
        id:14,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:98.00,
        sale:90.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product8,
        type:"Skillcare",
        qty:1,
    },    {
        id:15,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:98.00,
        sale:90.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product9,
        type:"Skillcare",
        qty:1,
    },    {
        id:16,
        name:"Cashmere Tank + Bag", 
        author:"By Evan Winter",
        price:98.00,
        sale:90.00,
        Descriptions:"Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in Reading at the age of 15, where she went to secretarial school and then into an insurance office",
        image:Product6,
        type:"Skillcare",
        qty:1,
    }
]